### ISSUE TITLE
Linux container System.IO.IOException: Failed to bind to address http://127.0.0.1:{PORT}: address already in use.

### ISSUE THREAD

**Issue by jrouaix** [AppMetrics/AspNetCoreHealth#9]
Hi, we are on the way to use AppMetrics to health check dotnet core services in kubernetes. 
We now have a little problem because of this lines : 
https://github.com/AppMetrics/AspNetCoreHealth/blob/23790037e09204f91bef024fd220a32087ac8300/src/App.Metrics.AspNetCore.Health.Endpoints/Builder/HealthAspNetEndpointWebHostBuilderExtensions.cs#L157-L162
On windows, while I ask to listen all interfaces like that :
![image](https://user-images.githubusercontent.com/2705498/40120115-bfb99ddc-591e-11e8-9a48-e997d0b08ffe.png)
It's working.
![image](https://user-images.githubusercontent.com/2705498/40120032-83728492-591e-11e8-9268-a5644bc2779d.png)

Then in a linux container : 
`System.IO.IOException: Failed to bind to address http://127.0.0.1:1337: address already in use.`

I have a quick workaround that I execute after called ConfigureAppHealthHostingConfiguration method : 
```
    var existingUrl = webHostBuilder.GetSetting(WebHostDefaults.ServerUrlsKey);
     var urls = existingUrl.Split(';');
     var newUrls = string.Join(";", urls.Where(u => !u.Contains("localhost")));
     webHostBuilder.UseSetting(WebHostDefaults.ServerUrlsKey, newUrls);
```

Dirty, but i my case, working.

**Comment by alhardy** [comment]
Thanks for opening this @jrouaix
